[theme]
primaryColor = "#10b981"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[server]
maxUploadSize = 100
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[logger]
level = "warning"